update script so that it increments the revision by default.

diff --git a/pushapi b/pushapi
--- a/pushapi
+++ b/pushapi
@@ -3,54 +3,105 @@
 #
 # pushapi
 #
-# A bash script that deploys of API bundles to the
-# Apigee Gateway.
+# A bash script that imports and possibly deploys API bundles to Apigee Edge. 
+#
+# Invoke with -h for help. 
+# usage examples: 
+# 
+# import api proxy named 'foo' to org 'org1':
+#     ./pushapi -v -o org1 foo
+#
+# import api proxy named 'foo' to org 'org1', and deploy it to env 'test':
+#     ./pushapi -v -o org1 -e test -d foo 
+#
+#
+# Last Saved: <2015-March-26 22:24:14>
+#
+# ----------------------------------------------------------------
+# 
+# Copyright (c) 2015 Dino Chiesa and Apigee Corp
+# All Rights Reserved.
+#
+# This code is licensed under a Revised BSD-style 3-clause license:
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are
+# met:
+#
+#    - Redistributions of source code must retain the above copyright
+#      notice, this list of conditions and the disclaimer that follows.
+#
+#    - Redistributions in binary form must reproduce the above copyright
+#      notice, this list of conditions and the disclaimer that follows in
+#      the documentation and/or other materials provided with the
+#      distribution.
+#
+#    - The name of the contributors may not be used to endorse or promote
+#      products derived from this software without specific prior written
+#      permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
+# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
+# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
+# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
+# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
+# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
+# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
+# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
+# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
 ## defaults
-environment=test
+version="Thursday, 26 March 2015, 14:50"
+#environment=test
+environment=""
 url=https://api.enterprise.apigee.com
 verbosity=2
 validate="&validate=true"
-deploy=1
+import=1
+deploy=0
 undeployonly=0
+removeall=0
 ziponly=0
 TAB=$'\t'
 
 # import .pushapi
-# This is just a file with credentials=user:password in it, and other default settings.
+# This is just a file with default settings in it. 
+# For example, you could include your credentials there. 
 #
 # NB: you should add .pushapi to the .gitignore to avoid uploading
 # apigee creds to github.
 
 # credentials=username:password
-# org=org-name
+# org=org_name
 # environment=environment_name (e.g. test)
-# url=api_management_url (as of coding, https://api.enterprise.apigee.com)
-# rev=revision_number (e.g. 1)
+# url=api_management_url (eg, https://api.enterprise.apigee.com)
 
 PDIRNAME=`dirname $0`
 . $PDIRNAME/.pushapi
-
-# TODO: should we default to creating a new revision?
-# TODO: this would require some conditional logic down below, I assume.
 
 function echoerror() { echo "$@" 1>&2; }
 
 function usage() {
   local CMD=`basename $0`
-  echo "$CMD: Deploy an API proxy to the Apigee Gateway."
+  echo "$CMD: Import and optionally deploy an API proxy to Apigee Edge. "
   echo "  Uses the curl utility, which must be available on the path."
+  echo "  $CMD version: ${version}"
   echo "usage: "
-  echo "  $CMD [options] application"
+  echo "  $CMD [options] apiproxy"
   echo "options: "
+  echo "  -h        display this message."
   echo "  -o org    the org to use."
   echo "  -e env    the environment to deploy to."
-  echo "  -r rev    the revision number to use."
-  echo "  -u url    the base server url to use."
-  echo "  -c creds  authn credentials for the API calls."
-  echo "  -x        undeploy & delete all revs of the API; do not deploy a new rev."
-  echo "  -z        just zip the bundle; do not deploy a new rev."
+  echo "  -d        deploy the revision. (default: no deploy). Requires environment (-e)"
+  echo "  -n name   override the name of the apiproxy. (default: use the directory name)"
+  echo "  -S url    the base server url to use."
+  echo "  -u creds  authn credentials for the API calls to the Edge management server."
+  echo "  -x        undeploy any revs of the API in the environment; do not deploy a new rev."
+  echo "  -X        undeploy & DELETE all revs of the API; do not deploy a new revision."
+  echo "  -z        just zip the bundle; do not deploy a new revision."
   echo "  -q        quiet; decrease verbosity by 1"
   echo "  -v        verbose; increase verbosity by 1"
   echo
@@ -58,8 +109,7 @@ function usage() {
   echo "  mgmt api url: $url"
   echo "  organization: $org"
   echo "   environment: $environment"
-  echo "      revision: $rev"
-  echo "   application: $application"
+  echo "      apiproxy: $apiproxy"
   echo "     verbosity: $verbosity"
   echo
   echo "You can specify default settings in the .pushapi file."
@@ -236,87 +286,6 @@ json_parse () {
 ## =======================================================
 
 
-starttime=$(timer)
-
-while getopts "vqhe:o:c:r:u:xzN" opt; do
-  case $opt in
-    h) usage ;;
-    q) verbosity=$(($verbosity-1)) ;;
-    v) verbosity=$(($verbosity+1)) ;;
-    e) environment=$OPTARG ;;
-    o) org=$OPTARG ;;
-    c) credentials=$OPTARG ;;
-    r) rev=$OPTARG ;;
-    u) url=$OPTARG ;;
-    x) undeployonly=1 && deploy=0 ;;
-    z) ziponly=1 && deploy=0 ;;
-    *) echo "unknown arg" && usage ;;
-  esac
-done
-
-shift $(($OPTIND - 1))
-
-## allow for an application directory that is not local
-if [ $# -gt 0 ]; then
-  appdir=$1
-  application=`basename $1`
-fi
-
-if [ "X$application" = "X" ]; then
-  echoerror "You must specify an application."
-  echoerror
-  usage
-  exit 1
-fi
-
-if [ $deploy -gt 0 ]; then
-  if [ ! -d "$1" ]; then
-      echoerror "The directory does not exist."
-      echoerror "The application name you specify must refer to a directory."
-      echoerror
-      usage
-      exit 1
-  fi
-fi
-
-if [ $ziponly -gt 0 -a $undeployonly -gt 0 ] ; then
-    echoerror "Mutually exclusive. Choose -x or -z ."
-    echoerror
-    usage
-    exit 1
-fi
-
-if [ $ziponly -eq 0 -a $undeployonly -eq 0 ] ; then
-  if ! [[ "$rev" =~ ^[0-9]+$ ]] ; then
-      echoerror "Bad revision: $rev"
-      echoerror "The revision must be a number."
-      echoerror
-      usage
-      exit 1
-  fi
-
-  if ! [[ "$url" =~ ^https?://.+$ ]] ; then
-      echoerror "Bad or missing mgmt api url: $url"
-      echoerror
-      usage
-      exit 1
-  fi
-
-  if [[ -z "$org" ]]; then 
-      echoerror "missing org"
-      echoerror
-      usage
-      exit 1
-  fi
-
-  if [[ -z "$environment" ]]; then 
-      echoerror "missing environment"
-      echoerror
-      usage
-      exit 1
-  fi
-fi
-
 
 ## function MYCURL_Q
 ## Print the curl command, omitting sensitive parameters, then run it.
@@ -379,11 +348,11 @@ function CleanupAndFinish() {
 }
 
 function DeleteApiproxyArchive() {
-  if [ -f $application.zip ]; then
+  if [ -f $apiproxy.zip ]; then
     if [ $verbosity -gt 0 ]; then
-      echo "Deleting $application.zip..."
+      echo "Deleting $apiproxy.zip..."
     fi
-    rm -rf $application.zip
+    rm -rf $apiproxy.zip
   fi
 }
 
@@ -394,11 +363,11 @@ function ProduceAndMaybeShowZip() {
   if [ $verbosity -gt 0 ]; then
     echo "Creating the zip..."
   fi
-  if [ -f $application.zip ]; then
+  if [ -f $apiproxy.zip ]; then
     if [ $verbosity -gt 0 ]; then
       echo "removing the zip..."
     fi
-    rm -rf $application.zip
+    rm -rf $apiproxy.zip
   fi
 
   curdir=`pwd`
@@ -419,21 +388,25 @@ function ProduceAndMaybeShowZip() {
   cd $curdir
   cd $appdir
 
-  zipout=`zip -r $curdir/$application.zip apiproxy -x "*/*.*~" -x "*/#*.*#" -x "*/node_modules/*"`
+  zipout=`zip -r $curdir/$apiproxy.zip apiproxy -x "*/*.*~" -x "*/#*.*#" -x "*/node_modules/*"`
   cd $curdir
 
   if [ $verbosity -gt 1 ]; then
     #echo $zipout
-    unzip -l $application.zip
+    unzip -l $apiproxy.zip
     echo
   fi
 }
 
-function UndeployAndDelete() {
-  local rev1
-  rev1=$1
 
-  MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$application/revisions/${rev1}/deployments"
+function MaybeUndeployAndMaybeDelete() {
+  local rev1
+  local env1
+  rev1=$1
+  env1=$2
+
+  # inquire deployment status
+  MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$proxyname/revisions/${rev1}/deployments"
   if [ ${CURL_RC} -eq 200 ]; then
     if [ $verbosity -gt 1 ]; then
       cat ${CURL_OUT}
@@ -453,34 +426,45 @@ function UndeployAndDelete() {
       declare -a env_array=(${deployed_envs})
 
       for env in ${env_array[@]}; do
-        if [ $verbosity -gt 0 ]; then
-          echo Undeploying from [${env}]...
+        # if [ $verbosity -gt 1 ]; then
+        #   echo considering env $env
+        # fi
+        if [  -z "$env1" -o "X$env1" = "X$env" ]; then
+          if [ $verbosity -gt 0 ]; then
+            echo revision $rev1: Undeploying from [${env}]...
+          fi
+          MYCURL_Q -u ${credentials} -X POST "${url}/v1/o/$org/apis/$proxyname/revisions/${rev1}/deployments?action=undeploy&env=${env}"
+          if [ $verbosity -gt 1 ]; then
+            cat ${CURL_OUT}
+            echo
+          fi
+          ## TODO: check return status, exit on fail.
+        else
+          if [ $verbosity -gt 0 ]; then
+            echo revision $rev1: Not deployed to env $env1. No un-deployment necessary...
+          fi
         fi
-        MYCURL_Q -u ${credentials} -X POST "${url}/v1/o/$org/apis/$application/revisions/${rev1}/deployments?action=undeploy&env=${env}"
-        if [ $verbosity -gt 1 ]; then
-          cat ${CURL_OUT}
-          echo
-        fi
-        ## TODO: check return status, exit on fail.
       done
+
     else
       if [ $verbosity -gt 0 ]; then
-        echo No un-deployment necessary.
-        echo That revision of the proxy does not appear to be currently deployed.
+        echo "revision $rev1: Not deployed; No un-deployment necessary."
       fi
     fi
 
-    if [ $verbosity -gt 0 ]; then
-      echo "Deleting the existing revision..."
-    fi
-    MYCURL_Q -u ${credentials} -X DELETE "${url}/v1/o/$org/apis/$application/revisions/${rev1}"
-    if [ $verbosity -gt 1 ]; then
-      cat ${CURL_OUT}
-      echo
-    fi
-    if [ ${CURL_RC} -ne 200 ]; then
-      echo The delete failed.
-      exit
+    if [ $removeall -gt 0 ]; then
+      if [ $verbosity -gt 0 ]; then
+        echo revision ${rev1}: Deleting the revision ...
+      fi
+      MYCURL_Q -u ${credentials} -X DELETE "${url}/v1/o/$org/apis/$proxyname/revisions/${rev1}"
+      if [ $verbosity -gt 1 ]; then
+        cat ${CURL_OUT}
+        echo
+      fi
+      if [ ${CURL_RC} -ne 200 ]; then
+        echo The delete failed.
+        exit
+      fi
     fi
 
   elif [ ${CURL_RC} -ne 404 ]; then
@@ -501,65 +485,166 @@ function UndeployAndDelete() {
 
 
 
+#------------------------------------------------------
+#
+# Start of execution
+#
+ 
+starttime=$(timer)
+
+while getopts "vqhe:o:S:u:xXzNd" opt; do
+  case $opt in
+    h) usage ;;
+    q) verbosity=$(($verbosity-1)) ;;
+    v) verbosity=$(($verbosity+1)) ;;
+    e) environment=$OPTARG ;;
+    o) org=$OPTARG ;;
+    n) proxyname=$OPTARG ;;
+    u) credentials=$OPTARG ;;
+    d) deploy=1 ;;
+    S) url=$OPTARG ;;
+    x) undeployonly=1 && import=0 ;;
+    X) removeall=1 && import=0 ;;
+    z) ziponly=1 && import=0 ;;
+    *) echo "unknown arg" && usage ;;
+  esac
+done
+
+shift $(($OPTIND - 1))
+
+## allow for an apiproxy directory that is not local
+if [ $# -gt 0 ]; then
+  appdir=$1
+  apiproxy=`basename $1`
+fi
+
+if [ "X$apiproxy" = "X" ]; then
+  echoerror "You must specify an apiproxy."
+  echoerror
+  usage
+  exit 1
+fi
+
+if [ "X$proxyname" = "X" ]; then
+  proxyname=$apiproxy
+fi
+
+if [ $import -gt 0 -o $ziponly -gt 0 ]; then
+  if [ ! -d "$1" ]; then
+      echoerror "The directory does not exist."
+      echoerror "The apiproxy name you specify must refer to a directory."
+      echoerror
+      usage
+      exit 1
+  fi
+fi
+
+if [ $ziponly -gt 0 -a $undeployonly -gt 0 ] ; then
+    echoerror "Mutually exclusive. Choose at most one of -x or -z ."
+    echoerror
+    usage
+    exit 1
+fi
+
+if [ $deploy -gt 0 -o $import -gt 0 -o $undeployonly -gt 0 -o $removeall -gt 0 ] ; then
+  
+  # if ! [[ "$rev" =~ ^[0-9]+$ ]] ; then
+  #     echoerror "Bad revision: $rev"
+  #     echoerror "The revision must be a number."
+  #     echoerror
+  #     usage
+  #     exit 1
+  # fi
+
+  if ! [[ "$url" =~ ^https?://.+$ ]] ; then
+      echoerror "Bad or missing mgmt api url: $url"
+      echoerror
+      usage
+      exit 1
+  fi
+
+  if [[ -z "$org" ]]; then 
+      echoerror "missing org"
+      echoerror
+      usage
+      exit 1
+  fi
+
+  if [ $deploy -gt 0 ]; then
+    # to deploy, we need to know the environment
+    if [[ -z "$environment" ]]; then 
+        echoerror "missing environment"
+        echoerror
+        usage
+        exit 1
+    fi
+  fi
+fi
+
+# arguments appear to be valid
+
+
 if [ $verbosity -gt 1 ]; then
   echo verbosity = $verbosity
 fi
 
 if [ $ziponly -gt 0 ]; then
   ProduceAndMaybeShowZip
-  echo "the zip is available as $application.zip"
+  echo "the zip is available as $apiproxy.zip"
 else 
 
-  if [ $verbosity -gt 0 ]; then
-    echo
-    echo "Getting deployments..."
-  fi
+  # We need to import (and maybe deploy) or undeploy
 
-  if [ $deploy -eq 0 ]; then
-    MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$application"
+  if [ $undeployonly -gt 0 -o $removeall -gt 0 ]; then
+    if [ $verbosity -gt 0 ]; then
+      echo
+      echo "Inquiring existing revisions..."
+    fi
+    MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$proxyname"
     if [ $verbosity -gt 1 ]; then
       cat ${CURL_OUT}
       echo
     fi
+
     if [ ${CURL_RC} -eq 200 ]; then
       output_parsed=`cat ${CURL_OUT} | json_tokenize | json_parse`
 
-      ##echo "${output_parsed}"
       echo "${output_parsed}" | grep --silent \"revision\"
       if [ $? -eq 0 ]; then
-        # There are existing deployed revisions
-        echo "Removing all revisions of that API Proxy..."
+        echo "There are existing revisions of that API Proxy"
 
-        deployed_revs=`echo "${output_parsed}" | grep \"revision\" | sed -E 's/\"//g' | sed -E 's/.+revision,[0-9]+.'"${TAB}"'//g'`
-        #echo "${deployed_revs}"
-        declare -a rev_array=(${deployed_revs})
-
+        existing_revs=`echo "${output_parsed}" | grep \"revision\" | sed -E 's/\"//g' | sed -E 's/.+revision,[0-9]+.'"${TAB}"'//g'`
+        #echo "${existing_revs}"
+        declare -a rev_array=(${existing_revs})
+        echo "${rev_array[@]}"
         for r1 in ${rev_array[@]}; do
-          UndeployAndDelete ${r1}
+          MaybeUndeployAndMaybeDelete ${r1} ${environment}
         done
       else
         echo "There are no existing revisions of that API Proxy."
       fi
 
-      if [ $verbosity -gt 0 ]; then
-        echo "Deleting the API Proxy..."
-      fi
-
-      MYCURL_Q -u ${credentials} -X DELETE "${url}/v1/o/$org/apis/$application"
-      if [ $verbosity -gt 1 ]; then
-        cat ${CURL_OUT}
-        echo
-      fi
-      if [ ${CURL_RC} -eq 200 ]; then
+      if [ $removeall -gt 0 ]; then
         if [ $verbosity -gt 0 ]; then
-          echo "deleted."
+          echo "Deleting the API Proxy..."
         fi
-      else
-        if [ $verbosity -lt 0 ]; then
+
+        MYCURL_Q -u ${credentials} -X DELETE "${url}/v1/o/$org/apis/$proxyname"
+        if [ $verbosity -gt 1 ]; then
           cat ${CURL_OUT}
           echo
         fi
-        echo "The DELETE failed."
+        if [ ${CURL_RC} -eq 200 ]; then
+          if [ $verbosity -gt 0 ]; then
+            echo "deleted."
+          fi
+        else
+          if [ $verbosity -lt 0 ]; then
+            cat ${CURL_OUT}
+            echo
+          fi
+          echo "The DELETE failed."
+        fi
       fi
 
     elif [ ${CURL_RC} -eq 401 ]; then
@@ -572,18 +657,16 @@ else
     fi
 
   else
-
-    # as necessary, un-deploy and delete the existing specific revision $rev
-    UndeployAndDelete $rev
+    # we want to import and maybe deploy
 
     # create the bundle zip
     ProduceAndMaybeShowZip
 
     # import
     if [ $verbosity -gt 0 ]; then
-      echo "Importing the bundle..."
+      echo "Importing the bundle as $proxyname..."
     fi
-    MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis?action=import&name=$application${validate}" -T $application.zip -H "Content-Type: application/octet-stream"
+    MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis?action=import&name=$proxyname${validate}" -T $apiproxy.zip -H "Content-Type: application/octet-stream"
     if [ $verbosity -gt 1 ]; then
       cat ${CURL_OUT}
       echo
@@ -603,16 +686,55 @@ else
       exit 1
     fi
 
-    # deploy
-    if [ $verbosity -gt 0 ]; then
-      echo "Deploying the API revision..."
-    fi
-    MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis/$application/revisions/$rev/deployments?action=deploy&env=$environment"
-    if [[ ! ${CURL_RC} =~ 200 ]]; then
-      echo
-      echoerror "There was an error deploying that revision of the API."
-      cat ${CURL_OUT} 1>&2;
-      echo
+    ## what revision did we just import? 
+    output_parsed=`cat ${CURL_OUT} | json_tokenize | json_parse`
+    rev=`echo "${output_parsed}" | grep \"revision\" | sed -E 's/\"//g'| sed -E 's/.+revision.'"${TAB}"'//g'`
+
+    echo This is revision $rev
+
+    if [ $deploy -gt 0 ]; then 
+      # if the request is to deploy, first we must un-deploy any
+      # existing revision from the target environment.
+      if [ $verbosity -gt 0 ]; then
+        echo
+        echo "Inquiring existing revisions..."
+      fi
+      MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$proxyname"
+      if [ $verbosity -gt 1 ]; then
+        cat ${CURL_OUT}
+        echo
+      fi
+
+      if [ ${CURL_RC} -eq 200 ]; then
+        output_parsed=`cat ${CURL_OUT} | json_tokenize | json_parse`
+
+        echo "${output_parsed}" | grep --silent \"revision\"
+        if [ $? -eq 0 ]; then
+
+          existing_revs=`echo "${output_parsed}" | grep \"revision\" | sed -E 's/\"//g' | sed -E 's/.+revision,[0-9]+.'"${TAB}"'//g'`
+          #echo "${existing_revs}"
+          declare -a rev_array=(${existing_revs})
+
+          for r1 in ${rev_array[@]}; do
+            if [ $r1 -ne $rev ]; then
+              MaybeUndeployAndMaybeDelete ${r1} $environment
+            fi 
+          done
+        fi
+      fi
+
+      # deploy
+      if [ $verbosity -gt 0 ]; then
+        #echo "revision $rev of API proxy $proxyname: Deploying to [${environment}]..."
+        echo "revision $rev: Deploying..."
+      fi
+      MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis/$proxyname/revisions/$rev/deployments?action=deploy&env=$environment"
+      if [[ ! ${CURL_RC} =~ 200 ]]; then
+        echo
+        echoerror "There was an error deploying revision $rev of $proxyname."
+        cat ${CURL_OUT} 1>&2;
+        echo
+      fi
     fi
     DeleteApiproxyArchive 
   fi
