myriad updates to this script

diff --git a/pushapi b/pushapi
--- a/pushapi
+++ b/pushapi
@@ -13,6 +13,8 @@ url=https://api.enterprise.apigee.com
 verbosity=2
 validate="&validate=true"
 deploy=1
+undeployonly=0
+ziponly=0
 TAB=$'\t'
 
 # import .pushapi
@@ -48,14 +50,15 @@ function usage() {
   echo "  -u url    the base server url to use."
   echo "  -c creds  authn credentials for the API calls."
   echo "  -x        undeploy & delete all revs of the API; do not deploy a new rev."
+  echo "  -z        just zip the bundle; do not deploy a new rev."
   echo "  -q        quiet; decrease verbosity by 1"
   echo "  -v        verbose; increase verbosity by 1"
   echo
   echo "Current parameter values:"
+  echo "  mgmt api url: $url"
   echo "  organization: $org"
   echo "   environment: $environment"
   echo "      revision: $rev"
-  echo "           url: $url"
   echo "   application: $application"
   echo "     verbosity: $verbosity"
   echo
@@ -235,7 +238,7 @@ json_parse () {
 
 starttime=$(timer)
 
-while getopts "vqhe:o:c:r:u:x" opt; do
+while getopts "vqhe:o:c:r:u:xz" opt; do
   case $opt in
     h) usage ;;
     q) verbosity=$(($verbosity-1)) ;;
@@ -245,8 +248,9 @@ while getopts "vqhe:o:c:r:u:x" opt; do
     c) credentials=$OPTARG ;;
     r) rev=$OPTARG ;;
     u) url=$OPTARG ;;
-    x) deploy=0 ;;
-    *) usage ;;
+    x) undeployonly=1 && deploy=0 ;;
+    z) ziponly=1 && deploy=0 ;;
+    *) echo "unknown arg" && usage ;;
   esac
 done
 
@@ -275,12 +279,42 @@ if [ $deploy -gt 0 ]; then
   fi
 fi
 
-if ! [[ "$rev" =~ ^[0-9]+$ ]] ; then
-    echoerror "Bad revision: $rev"
-    echoerror "The revision must be a number."
+if [ $ziponly -gt 0 -a $undeployonly -gt 0 ] ; then
+    echoerror "Mutually exclusive. Choose -x or -z ."
     echoerror
     usage
     exit 1
+fi
+
+if [ $ziponly -eq 0 -a $undeployonly -eq 0 ] ; then
+  if ! [[ "$rev" =~ ^[0-9]+$ ]] ; then
+      echoerror "Bad revision: $rev"
+      echoerror "The revision must be a number."
+      echoerror
+      usage
+      exit 1
+  fi
+
+  if ! [[ "$url" =~ ^https?://.+$ ]] ; then
+      echoerror "Bad or missing mgmt api url: $url"
+      echoerror
+      usage
+      exit 1
+  fi
+
+  if [[ -z "$org" ]]; then 
+      echoerror "missing org"
+      echoerror
+      usage
+      exit 1
+  fi
+
+  if [[ -z "$environment" ]]; then 
+      echoerror "missing environment"
+      echoerror
+      usage
+      exit 1
+  fi
 fi
 
 
@@ -329,6 +363,53 @@ function MYCURL_Q() {
   fi
 }
 
+function CleanupAndFinish() {
+  if [ -f ${CURL_OUT} ]; then
+    rm -rf ${CURL_OUT}
+  fi
+  if [ $verbosity -gt 1 ]; then
+    echo
+    echo "done"
+    date +"%Y-%m-%d %H:%M:%S"
+  fi
+  if [ $verbosity -gt 0 ]; then
+    printf 'Elapsed time: %s\n' $(timer $starttime)
+    echo
+  fi
+}
+
+function DeleteApiproxyArchive() {
+  if [ -f $application.zip ]; then
+    if [ $verbosity -gt 0 ]; then
+      echo "Deleting $application.zip..."
+    fi
+    rm -rf $application.zip
+  fi
+}
+
+function ProduceAndMaybeShowZip() {
+  local curdir
+  local zipout
+
+  if [ $verbosity -gt 0 ]; then
+    echo "Creating the zip..."
+  fi
+  if [ -f $application.zip ]; then
+    rm -rf $application.zip
+  fi
+
+  curdir=`pwd`
+  cd $appdir
+
+  zipout=`zip -r $curdir/$application.zip apiproxy -x "*/*.*~" -x "*/#*.*#"`
+  cd $curdir
+
+  if [ $verbosity -gt 1 ]; then
+    #echo $zipout
+    unzip -l $application.zip
+    echo
+  fi
+}
 
 function UndeployAndDelete() {
   local rev1
@@ -396,6 +477,7 @@ function UndeployAndDelete() {
     exit 1
   else
     echo No un-deployment necessary: That revision does not exist.
+    echo
   fi
 }
 
@@ -405,22 +487,26 @@ if [ $verbosity -gt 1 ]; then
   echo verbosity = $verbosity
 fi
 
-if [ $verbosity -gt 0 ]; then
-  echo
-  echo "Getting deployments..."
-fi
+if [ $ziponly -gt 0 ]; then
+  ProduceAndMaybeShowZip
+  echo "the zip is available as $application.zip"
+else 
 
-if [ $deploy -eq 0 ]; then
-  MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$application"
-  if [ $verbosity -gt 1 ]; then
-    cat ${CURL_OUT}
+  if [ $verbosity -gt 0 ]; then
     echo
+    echo "Getting deployments..."
   fi
-  if [ ${CURL_RC} -eq 200 ]; then
-    output_parsed=`cat ${CURL_OUT} | json_tokenize | json_parse`
 
-    ##echo "${output_parsed}"
-    if [ $verbosity -gt 0 ]; then
+  if [ $deploy -eq 0 ]; then
+    MYCURL_Q -u ${credentials} -X GET "${url}/v1/o/$org/apis/$application"
+    if [ $verbosity -gt 1 ]; then
+      cat ${CURL_OUT}
+      echo
+    fi
+    if [ ${CURL_RC} -eq 200 ]; then
+      output_parsed=`cat ${CURL_OUT} | json_tokenize | json_parse`
+
+      ##echo "${output_parsed}"
       echo "${output_parsed}" | grep --silent \"revision\"
       if [ $? -eq 0 ]; then
         # There are existing deployed revisions
@@ -433,112 +519,86 @@ if [ $deploy -eq 0 ]; then
         for r1 in ${rev_array[@]}; do
           UndeployAndDelete ${r1}
         done
-
       else
+        echo "There are no existing revisions of that API Proxy."
+      fi
+
+      if [ $verbosity -gt 0 ]; then
         echo "Deleting the API Proxy..."
       fi
-    fi
-    MYCURL_Q -u ${credentials} -X DELETE "${url}/v1/o/$org/apis/$application"
-    if [ $verbosity -gt 1 ]; then
-      cat ${CURL_OUT}
-      echo
-    fi
-    if [ ${CURL_RC} -eq 200 ]; then
-      if [ $verbosity -gt 0 ]; then
-        echo "deleted."
-      fi
-    else
-      if [ $verbosity -lt 0 ]; then
+
+      MYCURL_Q -u ${credentials} -X DELETE "${url}/v1/o/$org/apis/$application"
+      if [ $verbosity -gt 1 ]; then
         cat ${CURL_OUT}
         echo
       fi
-      echo "The DELETE failed."
+      if [ ${CURL_RC} -eq 200 ]; then
+        if [ $verbosity -gt 0 ]; then
+          echo "deleted."
+        fi
+      else
+        if [ $verbosity -lt 0 ]; then
+          cat ${CURL_OUT}
+          echo
+        fi
+        echo "The DELETE failed."
+      fi
+
+    elif [ ${CURL_RC} -eq 401 ]; then
+      echo "Not authorized to do that."
+    elif [ ${CURL_RC} -eq 404 ]; then
+      echo "No deployments found for that API proxy."
+    else
+      echo "status =" ${CURL_RC}
+      echo "Failed querying that API Proxy."
     fi
 
-  elif [ ${CURL_RC} -eq 401 ]; then
-    echo "Not authorized to do that."
   else
-    echo "status =" ${CURL_RC}
-    echo "Failed querying that API Proxy."
-  fi
 
-else
+    # as necessary, un-deploy and delete the existing specific revision $rev
+    UndeployAndDelete $rev
 
-  # as necessary, un-deploy and delete the existing specific revision $rev
-  UndeployAndDelete $rev
+    # create the bundle zip
+    ProduceAndMaybeShowZip
 
-  if [ $verbosity -gt 0 ]; then
-    echo "Creating the zip..."
-  fi
-  # create the bundle zip
-  if [ -f $application.zip ]; then
-    rm -rf $application.zip
-  fi
-
-  curdir=`pwd`
-  cd $appdir
-
-  ZIP_OUT=`zip -r $curdir/$application.zip apiproxy -x "*/*.*~"`
-  cd $curdir
-
-  if [ $verbosity -gt 1 ]; then
-    #echo $ZIP_OUT
-    unzip -l $application.zip
-    echo
-  fi
-
-  # import
-  if [ $verbosity -gt 0 ]; then
-    echo "Importing the bundle..."
-  fi
-  MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis?action=import&name=$application${validate}" -T $application.zip -H "Content-Type: application/octet-stream"
-  if [ $verbosity -gt 1 ]; then
-    cat ${CURL_OUT}
-    echo
-    echo
-  fi
-
-  if [ ${CURL_RC} -ne 201 ]; then
-    echo
-    if [ $verbosity -le 1 ]; then
+    # import
+    if [ $verbosity -gt 0 ]; then
+      echo "Importing the bundle..."
+    fi
+    MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis?action=import&name=$application${validate}" -T $application.zip -H "Content-Type: application/octet-stream"
+    if [ $verbosity -gt 1 ]; then
       cat ${CURL_OUT}
       echo
+      echo
     fi
-    echoerror "There was an error importing that API bundle..."
-    echo
-    exit 1
-  fi
 
-  # deploy
-  if [ $verbosity -gt 0 ]; then
-    echo "Deploying the API revision..."
-  fi
-  MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis/$application/revisions/$rev/deployments?action=deploy&env=$environment"
-  if [[ ! ${CURL_RC} =~ 200 ]]; then
-    echo
-    echoerror "There was an error deploying that revision of the API."
-    cat ${CURL_OUT} 1>&2;
-    echo
-  fi
+    if [ ${CURL_RC} -ne 201 ]; then
+      echo
+      if [ $verbosity -le 1 ]; then
+        cat ${CURL_OUT}
+        echo
+      fi
+      echoerror "There was an error importing that API bundle..."
+      DeleteApiproxyArchive
+      echo
+      CleanupAndFinish
+      exit 1
+    fi
 
-  if [ -f $application.zip ]; then
+    # deploy
     if [ $verbosity -gt 0 ]; then
-      echo "Deleting $application.zip..."
+      echo "Deploying the API revision..."
     fi
-    rm -rf $application.zip
+    MYCURL_Q -u $credentials -X POST "$url/v1/o/$org/apis/$application/revisions/$rev/deployments?action=deploy&env=$environment"
+    if [[ ! ${CURL_RC} =~ 200 ]]; then
+      echo
+      echoerror "There was an error deploying that revision of the API."
+      cat ${CURL_OUT} 1>&2;
+      echo
+    fi
+    DeleteApiproxyArchive 
   fi
+
 fi
 
-
-if [ -f ${CURL_OUT} ]; then
-  rm -rf ${CURL_OUT}
-fi
-if [ $verbosity -gt 1 ]; then
-  echo
-  echo "done"
-  date +"%Y-%m-%d %H:%M:%S"
-fi
-if [ $verbosity -gt 0 ]; then
-  printf 'Elapsed time: %s\n' $(timer $starttime)
-  echo
-fi
+CleanupAndFinish
